USE inmers;
INSERT INTO generic_medicines (name, is_active, createdAt, updatedAt)
VALUES
('0.9% Sodium Chloride', TRUE, NOW(), NOW()),
('10% Dextrose in Water', TRUE, NOW(), NOW()),
('3% Hypertonic Saline Solution (for diagnosis of pulmonary tuberculosis)', TRUE, NOW(), NOW()),
('5% Dextrose in 0.3% Sodium Chloride', TRUE, NOW(), NOW()),
('5% Dextrose in 0.45% Sodium Chloride', TRUE, NOW(), NOW()),
('5% Dextrose in 0.9% Sodium Chloride', TRUE, NOW(), NOW()),
('5% Dextrose in Lactated Ringers', TRUE, NOW(), NOW()),
('5% Dextrose in Water', TRUE, NOW(), NOW()),
('Abacavir', TRUE, NOW(), NOW()),
('Acetated Ringer’s Solution', TRUE, NOW(), NOW()),
('Acetazolamide ', TRUE, NOW(), NOW()),
('Acetylcysteine', TRUE, NOW(), NOW()),
('Aciclovir', TRUE, NOW(), NOW()),
('Activated Charcoal', TRUE, NOW(), NOW()),
('Adenosine ', TRUE, NOW(), NOW()),
('Adrenaline (see Epinephrine)', TRUE, NOW(), NOW()),
('Albendazole', TRUE, NOW(), NOW()),
('Albumin, Human ', TRUE, NOW(), NOW()),
('Alcohol, Ethyl ', TRUE, NOW(), NOW()),
('Alendronate (as sodium salt)', TRUE, NOW(), NOW()),
('Alendronate + Cholecalciferol (vitamin D3)', TRUE, NOW(), NOW()),
('Alfuzosin (as hydrochloride)', TRUE, NOW(), NOW()),
('All‐in‐one Admixtures', TRUE, NOW(), NOW()),
('Allopurinol', TRUE, NOW(), NOW()),
('Alprazolam ', TRUE, NOW(), NOW()),
('Aluminum Hydroxide + Magnesium Hydroxide', TRUE, NOW(), NOW()),
('Amikacin (as sulfate)', TRUE, NOW(), NOW()),
('Amino Acid + carbohydrate + multivitamins + electrolytes', TRUE, NOW(), NOW()),
('Amino Acid + glucose + electrolytes + vitamin B1', TRUE, NOW(), NOW()),
('Amino Acid Solutions for Hepatic Failure', TRUE, NOW(), NOW()),
('Amino Acid Solutions for Immunonutrition / Immunoenhancement', TRUE, NOW(), NOW()),
('Amino Acid Solutions for Infants', TRUE, NOW(), NOW()),
('Amino Acid Solutions for Renal Condition', TRUE, NOW(), NOW()),
('Amino Acids, Crystalline Standard', TRUE, NOW(), NOW()),
('Aminophylline (theophylline ethylenediamine) ', TRUE, NOW(), NOW()),
('Amiodarone (as hydrochloride) ', TRUE, NOW(), NOW()),
('Amlodipine (as besilate/camsylate)', TRUE, NOW(), NOW()),
('Amoxicillin (as trihydrate)', TRUE, NOW(), NOW()),
('Amoxicillin + Potassium Clavulanate (see Co‐Amoxiclav)', TRUE, NOW(), NOW()),
('Amphotericin B deoxycholate', TRUE, NOW(), NOW()),
('Amphotericin B (Lipid Complex) (as cholesteryl complex, colloidal dispersion)', TRUE, NOW(), NOW()),
('Ampicillin (as sodium salt)', TRUE, NOW(), NOW()),
('Ampicillin + Sulbactam', TRUE, NOW(), NOW()),
('Anastrazole', TRUE, NOW(), NOW()),
('Anti‐D Immunoglobulin (human anti‐D immunoglobulin)', TRUE, NOW(), NOW()),
('Antilymphocyte Immunoglobulin (ALG) (equine) ', TRUE, NOW(), NOW()),
('Anti‐rabies serum (equine)', TRUE, NOW(), NOW()),
('Anti‐tetanus serum (equine)', TRUE, NOW(), NOW()),
('Antithymocyte Immunoglobulin (ATG) (rabbit) ', TRUE, NOW(), NOW()),
('Aripiprazole', TRUE, NOW(), NOW()),
('Artemether + Lumefantrin ', TRUE, NOW(), NOW()),
('Artesunate', TRUE, NOW(), NOW()),
('AS04 Adjuvanted)', TRUE, NOW(), NOW()),
('Ascorbic Acid (vitamin C)', TRUE, NOW(), NOW()),
('Asparaginase ', TRUE, NOW(), NOW()),
('Aspirin', TRUE, NOW(), NOW()),
('Atenolol', TRUE, NOW(), NOW()),
('Atorvastatin calcium', TRUE, NOW(), NOW()),
('Atracurium (as besilate)', TRUE, NOW(), NOW()),
('Atropine (as sulfate) ', TRUE, NOW(), NOW()),
('Azathioprine  ', TRUE, NOW(), NOW()),
('Azithromycin', TRUE, NOW(), NOW()),
('Aztreonam', TRUE, NOW(), NOW()),
('Bacitracin + Neomycin + Polymixin B', TRUE, NOW(), NOW()),
('Baclofen', TRUE, NOW(), NOW()),
('Balanced Multiple Maintenance Solution', TRUE, NOW(), NOW()),
('Balanced Multiple Replacement Solution', TRUE, NOW(), NOW()),
('Balanced Multiple Replacement Solution w/ pH 7.4', TRUE, NOW(), NOW()),
('Barium Sulfate', TRUE, NOW(), NOW()),
('Basiliximab ', TRUE, NOW(), NOW()),
('BCG Vaccine', TRUE, NOW(), NOW()),
('Bedaquiline fumarate', TRUE, NOW(), NOW()),
('Benzoyl Peroxide', TRUE, NOW(), NOW()),
('Benzyl Benzoate', TRUE, NOW(), NOW()),
('Beractant', TRUE, NOW(), NOW()),
('Betahistine (as hydrochloride/ dihydrochloride)', TRUE, NOW(), NOW()),
('Betamethasone', TRUE, NOW(), NOW()),
('Betaxolol (as hydrochloride)', TRUE, NOW(), NOW()),
('Bicalutamide', TRUE, NOW(), NOW()),
('Biperiden', TRUE, NOW(), NOW()),
('Biphasic Isophane Human Insulin 70/30 (recombinant DNA)', TRUE, NOW(), NOW()),
('Bisacodyl', TRUE, NOW(), NOW()),
('Bisoprolol', TRUE, NOW(), NOW()),
('Bleomycin (as sulfate) ', TRUE, NOW(), NOW()),
('Brimonidine (as tartrate)', TRUE, NOW(), NOW()),
('Brinzolamide', TRUE, NOW(), NOW()),
('Bromazepam ', TRUE, NOW(), NOW()),
('Bromocriptine (as mesilate) ', TRUE, NOW(), NOW()),
('Budesonide', TRUE, NOW(), NOW()),
('Budesonide + Formoterol', TRUE, NOW(), NOW()),
('Bumetanide', TRUE, NOW(), NOW()),
('Bupivacaine (as hydrochloride) ', TRUE, NOW(), NOW()),
('Butamirate (as citrate) ', TRUE, NOW(), NOW()),
('Butorphanol (as tartrate) ', TRUE, NOW(), NOW()),
('Calamine, Plain', TRUE, NOW(), NOW()),
('Calcipotriol', TRUE, NOW(), NOW()),
('Calcipotriol + Betamethasone', TRUE, NOW(), NOW()),
('Calcitriol ', TRUE, NOW(), NOW()),
('Calcium', TRUE, NOW(), NOW()),
('Calcium Carbonate', TRUE, NOW(), NOW()),
('Calcium Carbonate + Cholecalciferol (vitamin D3)', TRUE, NOW(), NOW()),
('Calcium Folinate (leucovorin calcium)', TRUE, NOW(), NOW()),
('Calcium Gluconate ', TRUE, NOW(), NOW()),
('Calcium Sennosides (equivalent to Standardized Senna concentrate)', TRUE, NOW(), NOW()),
('Capecitabine ', TRUE, NOW(), NOW()),
('Capreomycin', TRUE, NOW(), NOW()),
('Captopril', TRUE, NOW(), NOW()),
('Carbachol', TRUE, NOW(), NOW()),
('Carbamazepine', TRUE, NOW(), NOW()),
('Carbetocin', TRUE, NOW(), NOW()),
('Carboplatin ', TRUE, NOW(), NOW()),
('Carboprost', TRUE, NOW(), NOW()),
('Carboxymethylcellulose (as sodium)', TRUE, NOW(), NOW()),
('Carvedilol', TRUE, NOW(), NOW()),
('Castor Oil', TRUE, NOW(), NOW()),
('Cefalexin (as monohydrate)', TRUE, NOW(), NOW()),
('Cefazolin (as sodium salt)', TRUE, NOW(), NOW()),
('Cefepime', TRUE, NOW(), NOW()),
('Cefixime', TRUE, NOW(), NOW()),
('Cefotaxime (as sodium salt)', TRUE, NOW(), NOW()),
('Cefoxitin', TRUE, NOW(), NOW()),
('Ceftaxidime (Ceftazidime)', TRUE, NOW(), NOW()),
('Ceftriaxone (as disodium/sodium salt)', TRUE, NOW(), NOW()),
('Cefuroxime', TRUE, NOW(), NOW()),
('Celecoxib', TRUE, NOW(), NOW()),
('Cetirizine (as dihydrochloride)', TRUE, NOW(), NOW()),
('Chlorambucil ', TRUE, NOW(), NOW()),
('Chloramphenicol', TRUE, NOW(), NOW()),
('Chlorhexidine', TRUE, NOW(), NOW()),
('Chloroquine (as phosphate or diphosphate)', TRUE, NOW(), NOW()),
('Chlorphenamine (Chlopheniramine) (as maleate)', TRUE, NOW(), NOW()),
('Chlorpheniramine (see Chlorphenamine)', TRUE, NOW(), NOW()),
('Chlorpromazine (as hydrochloride)', TRUE, NOW(), NOW()),
('Ciclosporin ', TRUE, NOW(), NOW()),
('Cilostazol', TRUE, NOW(), NOW()),
('Cinnarizine', TRUE, NOW(), NOW()),
('Ciprofloxacin', TRUE, NOW(), NOW()),
('Cisplatin ', TRUE, NOW(), NOW()),
('Clarithromycin', TRUE, NOW(), NOW()),
('Clindamycin', TRUE, NOW(), NOW()),
('Clobetasol (as propionate)', TRUE, NOW(), NOW()),
('Clofazimine ', TRUE, NOW(), NOW()),
('Clomifene ', TRUE, NOW(), NOW()),
('Clonazepam ', TRUE, NOW(), NOW()),
('Clonidine', TRUE, NOW(), NOW()),
('Clopidogrel', TRUE, NOW(), NOW()),
('Clotrimazole', TRUE, NOW(), NOW()),
('Cloxacillin (as sodium salt)', TRUE, NOW(), NOW()),
('Clozapine ', TRUE, NOW(), NOW()),
('Co-Amoxiclav (amoxicillin + potassium clavulanate)', TRUE, NOW(), NOW()),
('Cobra Antivenin', TRUE, NOW(), NOW()),
('Codeine ', TRUE, NOW(), NOW()),
('Colchicine', TRUE, NOW(), NOW()),
('Colistin', TRUE, NOW(), NOW()),
('Combined Glucose-Amino Acid Solutions', TRUE, NOW(), NOW()),
('Conjugated Estrogen', TRUE, NOW(), NOW()),
('Cotrimoxazole (sulfamethoxazole + trimethoprim)', TRUE, NOW(), NOW()),
('Crotamiton', TRUE, NOW(), NOW()),
('Cyclophosphamide ', TRUE, NOW(), NOW()),
('Cycloserine', TRUE, NOW(), NOW()),
('Cyproterone (as acetate) ', TRUE, NOW(), NOW()),
('Cytarabine ', TRUE, NOW(), NOW()),
('Dacarbazine ', TRUE, NOW(), NOW()),
('Daclatasvir', TRUE, NOW(), NOW()),
('Dactinomycin ', TRUE, NOW(), NOW()),
('Danazol ', TRUE, NOW(), NOW()),
('Dantrolene (as sodium salt)', TRUE, NOW(), NOW()),
('Dapsone ', TRUE, NOW(), NOW()),
('Deferasirox', TRUE, NOW(), NOW()),
('Deferiprone ', TRUE, NOW(), NOW()),
('Deferoxamine (as mesilate)', TRUE, NOW(), NOW()),
('Delamanid', TRUE, NOW(), NOW()),
('Desflurane ', TRUE, NOW(), NOW()),
('Desmopressin (as acetate)', TRUE, NOW(), NOW()),
('Dexamethasone', TRUE, NOW(), NOW()),
('Dextran, High Molecular Weight (Dextran 70)', TRUE, NOW(), NOW()),
('Dextromethorphan (as hydrobromide) ', TRUE, NOW(), NOW()),
('Diazepam (1, A1)', TRUE, NOW(), NOW()),
('Diclofenac', TRUE, NOW(), NOW()),
('Dicycloverine (Dicyclomine) (as hydrochloride)', TRUE, NOW(), NOW()),
('Diethylcarbamazine', TRUE, NOW(), NOW()),
('Digoxin ', TRUE, NOW(), NOW()),
('Diloxanide (as furoate)', TRUE, NOW(), NOW()),
('Diltiazem (as hydrochloride)', TRUE, NOW(), NOW()),
('Dimeglumine Gadopentetate', TRUE, NOW(), NOW()),
('Dimercaprol ', TRUE, NOW(), NOW()),
('Dimercaptopropane-sulphonate (DMPS) ', TRUE, NOW(), NOW()),
('Diphenhydramine (as hydrochloride)', TRUE, NOW(), NOW()),
('Diphtheria Antitoxin', TRUE, NOW(), NOW()),
('Diphtheria, Tetanus, Pertussis, Hepatitis B Recombinant and Haemophilus Influenza Type B (Hib) Combined Vaccine', TRUE, NOW(), NOW()),
('Diphtheria-Tetanus Toxoids (DT)', TRUE, NOW(), NOW()),
('Diphtheria-Tetanus Toxoids (Td)', TRUE, NOW(), NOW()),
('Diphtheria-Tetanus Toxoids and Acellular Pertussis Vaccines (DTaP)', TRUE, NOW(), NOW()),
('Diphtheria-Tetanus Toxoids and Pertussis Vaccine (DTP)', TRUE, NOW(), NOW()),
('Dipyridamole ', TRUE, NOW(), NOW()),
('Divalproex Sodium OR Sodium Valproate + Valproic Acid', TRUE, NOW(), NOW()),
('Dobutamine ', TRUE, NOW(), NOW()),
('Docetaxel ', TRUE, NOW(), NOW()),
('Dolutegravir', TRUE, NOW(), NOW()),
('Domperidone', TRUE, NOW(), NOW()),
('Donepezil', TRUE, NOW(), NOW()),
('Dopamine (as hydrochloride) ', TRUE, NOW(), NOW()),
('Dorzolamide', TRUE, NOW(), NOW()),
('Doxorubicin (as hydrochloride) ', TRUE, NOW(), NOW()),
('Doxycycline', TRUE, NOW(), NOW()),
('DTaP + Hib', TRUE, NOW(), NOW()),
('DTP + Hepatitis B Vaccine (recombinant)', TRUE, NOW(), NOW()),
('DTP + Hib', TRUE, NOW(), NOW()),
('DTP + Inactivated Polio Vaccine (IPV)', TRUE, NOW(), NOW()),
('DTP + IPV + Hib', TRUE, NOW(), NOW()),
('Dydrogesterone', TRUE, NOW(), NOW()),
('Efavirenz', TRUE, NOW(), NOW()),
('Emtricitabine + Tenofovir Disoproxil Fumarate', TRUE, NOW(), NOW()),
('Enalapril (as maleate)', TRUE, NOW(), NOW()),
('Enalapril + Hydrochlorothiazide', TRUE, NOW(), NOW()),
('Enoxaparin (as sodium salt) ', TRUE, NOW(), NOW()),
('Entecavir', TRUE, NOW(), NOW()),
('Enteral Nutrition - Adult Polymeric', TRUE, NOW(), NOW()),
('Enteral Nutrition - Disease Specific', TRUE, NOW(), NOW()),
('Enteral Nutrition - Fiber Containing', TRUE, NOW(), NOW()),
('Enteral Nutrition - Modular', TRUE, NOW(), NOW()),
('Enteral Nutrition - Pediatric Polymeric', TRUE, NOW(), NOW()),
('Enteral Nutrition - Semi- Elemental', TRUE, NOW(), NOW()),
('Eperisone hydrochloride', TRUE, NOW(), NOW()),
('Ephedrine ', TRUE, NOW(), NOW()),
('Epinephrine (adrenaline) ', TRUE, NOW(), NOW()),
('Epirubicin (as hydrochloride) ', TRUE, NOW(), NOW()),
('Epoetin Alfa (recombinant human erythropoietin) ', TRUE, NOW(), NOW()),
('Epoetin Beta (recombinant erythropoietin) ', TRUE, NOW(), NOW()),
('Ergotamine ', TRUE, NOW(), NOW()),
('Ertapenem', TRUE, NOW(), NOW()),
('Erythromycin', TRUE, NOW(), NOW()),
('Escitalopram (as oxalate)', TRUE, NOW(), NOW()),
('Esmolol (as hydrochloride) ', TRUE, NOW(), NOW()),
('Ethambutol (as hydrochloride)', TRUE, NOW(), NOW()),
('Ethinylestradiol + Desogestrel', TRUE, NOW(), NOW()),
('Ethinylestradiol + Norethisterone', TRUE, NOW(), NOW()),
('Ethinylestradiol + Norgestrel', TRUE, NOW(), NOW()),
('Ethinylestradiol + Levonorgestrel', TRUE, NOW(), NOW()),
('Etonogestrel', TRUE, NOW(), NOW()),
('Etoposide ', TRUE, NOW(), NOW()),
('Everolimus', TRUE, NOW(), NOW()),
('Factor IX Complex Concentrate (coagulation factors II, VII, IX, X) ', TRUE, NOW(), NOW()),
('Factor VIII Concentrate ', TRUE, NOW(), NOW()),
('Famotidine', TRUE, NOW(), NOW()),
('Felodipine', TRUE, NOW(), NOW()),
('Fenofibrate ', TRUE, NOW(), NOW()),
('Fentanyl (as citrate) ', TRUE, NOW(), NOW()),
('Ferrous Salt', TRUE, NOW(), NOW()),
('Ferrous Salt + Folic Acid', TRUE, NOW(), NOW()),
('Filgrastim (G-CSF) ', TRUE, NOW(), NOW()),
('Finasteride', TRUE, NOW(), NOW()),
('Fluconazole', TRUE, NOW(), NOW()),
('Flucytosine (5-fluorocytosine) ', TRUE, NOW(), NOW()),
('Flumazenil ', TRUE, NOW(), NOW()),
('Flunarizine (as hydrochloride)', TRUE, NOW(), NOW()),
('Fluocinonide', TRUE, NOW(), NOW()),
('Fluorescein (as sodium salt)', TRUE, NOW(), NOW()),
('Fluorouracil ', TRUE, NOW(), NOW()),
('Fluoxetine ', TRUE, NOW(), NOW()),
('Flupentixol (as decanoate) ', TRUE, NOW(), NOW()),
('Fluphenazine (as decanoate) ', TRUE, NOW(), NOW()),
('Flutamide ', TRUE, NOW(), NOW()),
('Fluticasone (as propionate)', TRUE, NOW(), NOW()),
('Fluticasone (as propionate) + Salmeterol (as xinafoate)', TRUE, NOW(), NOW()),
('Fluticasone (as propionate) + Formoterol (as fumarate dihydrate)', TRUE, NOW(), NOW()),
('Folic Acid', TRUE, NOW(), NOW()),
('Fomepizole (4 – methylprazole) ', TRUE, NOW(), NOW()),
('Fondaparinux (as sodium salt)', TRUE, NOW(), NOW()),
('Formoterol', TRUE, NOW(), NOW()),
('Fosfomycin', TRUE, NOW(), NOW()),
('Furosemide', TRUE, NOW(), NOW()),
('Fusidate Sodium / Fusidic Acid', TRUE, NOW(), NOW()),
('Gabapentin', TRUE, NOW(), NOW()),
('Gadobutrol', TRUE, NOW(), NOW()),
('Gadoteric acid', TRUE, NOW(), NOW()),
('Ganciclovir', TRUE, NOW(), NOW()),
('Gas Forming Agent', TRUE, NOW(), NOW()),
('Gemcitabine (as hydrochloride) ', TRUE, NOW(), NOW()),
('Gentamicin (as sulfate)', TRUE, NOW(), NOW()),
('Gliclazide', TRUE, NOW(), NOW()),
('Glucagon (as hydrochloride) ', TRUE, NOW(), NOW()),
('Glucose (dextrose)', TRUE, NOW(), NOW()),
('Glycerin (see Glycerol)', TRUE, NOW(), NOW()),
('Glycerol (glycerin)', TRUE, NOW(), NOW()),
('Glyceryl trinitrate (nitroglycerin)', TRUE, NOW(), NOW()),
('Goserelin (as acetate)', TRUE, NOW(), NOW()),
('Haloperidol ', TRUE, NOW(), NOW()),
('Halothane ', TRUE, NOW(), NOW()),
('Hemodialysis Solution', TRUE, NOW(), NOW()),
('Hemophilus Influenzae type B Conjugated Vaccine (Hib)', TRUE, NOW(), NOW()),
('Heparin (unfractionated) (as sodium salt) ', TRUE, NOW(), NOW()),
('Hepatitis A Inactivated Vaccine', TRUE, NOW(), NOW()),
('Hepatitis B Immunoglobulin (human)', TRUE, NOW(), NOW()),
('Hepatitis B Vaccine (recombinant DNA)', TRUE, NOW(), NOW()),
('Human Papillomavirus vaccine types 16 and 18 (Recombinant,', TRUE, NOW(), NOW()),
('Human Papillomavirus quadrivalent (types 6, 11, 16, 18) recombinant vaccine', TRUE, NOW(), NOW()),
('Human Recombinant Tissue Type Plasminogen Activator (Alteplase) ', TRUE, NOW(), NOW()),
('Hydralazine (as hydrochloride)', TRUE, NOW(), NOW()),
('Hydrochlorothiazide', TRUE, NOW(), NOW()),
('Hydrocortisone', TRUE, NOW(), NOW()),
('Hydrogen Peroxide', TRUE, NOW(), NOW()),
('Hydroxychloroquine (as sulfate)', TRUE, NOW(), NOW()),
('Hydroxyethyl Starch', TRUE, NOW(), NOW()),
('Hydroxyurea ', TRUE, NOW(), NOW()),
('Hydroxyzine (as dihydrochloride)', TRUE, NOW(), NOW()),
('Hyoscine (as N-butyl bromide)', TRUE, NOW(), NOW()),
('Hypertonic lactate', TRUE, NOW(), NOW()),
('Hypromellose', TRUE, NOW(), NOW()),
('Ibuprofen', TRUE, NOW(), NOW()),
('Idarubicin (as hydrochloride) ', TRUE, NOW(), NOW()),
('Ifosfamide ', TRUE, NOW(), NOW()),
('Imatinib (as mesilate) ', TRUE, NOW(), NOW()),
('Imiglucerase', TRUE, NOW(), NOW()),
('Imiquimod', TRUE, NOW(), NOW()),
('Immunoglobulin Normal, Human (IGIV) ', TRUE, NOW(), NOW()),
('Immunoglobulin Normal, Human (IGIM)', TRUE, NOW(), NOW()),
('Inactivated Polio Vaccine (Types 1, 2, and 3), Salk', TRUE, NOW(), NOW()),
('Inactivated Poliomyelitis Vaccine (Types 1, 2 and 3)', TRUE, NOW(), NOW()),
('Indacaterol (as maleate) + glycopyrronium (as bromide)', TRUE, NOW(), NOW()),
('Indapamide', TRUE, NOW(), NOW()),
('Influenza Polyvalent Vaccine', TRUE, NOW(), NOW()),
('Interferon Alfa 2B (human) ', TRUE, NOW(), NOW()),
('Intraocular Irrigating Solution (balanced salt solution)', TRUE, NOW(), NOW()),
('Iodine', TRUE, NOW(), NOW()),
('Iodixanol', TRUE, NOW(), NOW()),
('Iodized Oil Fluid', TRUE, NOW(), NOW()),
('Iohexol', TRUE, NOW(), NOW()),
('Iopamidol', TRUE, NOW(), NOW()),
('Iopromide', TRUE, NOW(), NOW()),
('Iothalamate', TRUE, NOW(), NOW()),
('Ioversol', TRUE, NOW(), NOW()),
('Ipratropium (as bromide)', TRUE, NOW(), NOW()),
('Ipratropium (as bromide) + Fenoterol (as hydrobromide)', TRUE, NOW(), NOW()),
('Ipratropium + Salbutamol', TRUE, NOW(), NOW()),
('Irbesartan', TRUE, NOW(), NOW()),
('Irbesartan + Hydrochlorothiazide', TRUE, NOW(), NOW()),
('Irinotecan (as hydrochloride) ', TRUE, NOW(), NOW()),
('Iron sucrose', TRUE, NOW(), NOW()),
('Isoflurane ', TRUE, NOW(), NOW()),
('Isoniazid', TRUE, NOW(), NOW()),
('Isoniazid + Rifampicin ', TRUE, NOW(), NOW()),
('Isoniazid + Rifampicin + Pyrazinamide ', TRUE, NOW(), NOW()),
('Isoniazid + Rifampicin + Ethambutol ', TRUE, NOW(), NOW()),
('Isoniazid + Rifampicin + Pyrazinamide + Ethambutol ', TRUE, NOW(), NOW()),
('Isophane Insulin Human (recombinant DNA)', TRUE, NOW(), NOW()),
('Isosorbide Dinitrate', TRUE, NOW(), NOW()),
('Isosorbide-5-Mononitrate', TRUE, NOW(), NOW()),
('Isotonic electrolyte solution for IV infusion', TRUE, NOW(), NOW()),
('Isoxsuprine (as hydrochloride)', TRUE, NOW(), NOW()),
('Itraconazole', TRUE, NOW(), NOW()),
('Ivermectin', TRUE, NOW(), NOW()),
('Kanamycin (as sulfate)', TRUE, NOW(), NOW()),
('Ketamine (as hydrochloride)', TRUE, NOW(), NOW()),
('Ketoconazole', TRUE, NOW(), NOW()),
('Ketoprofen', TRUE, NOW(), NOW()),
('Ketorolac (as tromethamol)', TRUE, NOW(), NOW()),
('Lactated Ringer\'s Solution (Ringer\'s Lactate)', TRUE, NOW(), NOW()),
('Lactulose', TRUE, NOW(), NOW()),
('Lagundi ● [Vitex negundo L. ( Fam. Verbenaceae)]', TRUE, NOW(), NOW()),
('Lamivudine', TRUE, NOW(), NOW()),
('Lamivudine + Efavirenz + Tenofovir', TRUE, NOW(), NOW()),
('Lamivudine + Zidovudine', TRUE, NOW(), NOW()),
('Lamivudine + Zidovudine + Nevirapine', TRUE, NOW(), NOW()),
('Lamivudine +Tenofovir', TRUE, NOW(), NOW()),
('Lamotrigine', TRUE, NOW(), NOW()),
('Lansoprazole', TRUE, NOW(), NOW()),
('Latanoporst + Timolol maleate', TRUE, NOW(), NOW()),
('Latanoprost', TRUE, NOW(), NOW()),
('Letrozole', TRUE, NOW(), NOW()),
('Leucovorin Calcium (see Calcium Folinate) ', TRUE, NOW(), NOW()),
('Leuproreline (as acetate) ', TRUE, NOW(), NOW()),
('Levetiracetam', TRUE, NOW(), NOW()),
('Levobupivacaine', TRUE, NOW(), NOW()),
('Levodopa + Carbidopa', TRUE, NOW(), NOW()),
('Levofloxacin', TRUE, NOW(), NOW()),
('Levothyroxine (as sodium/anhydrous sodium)', TRUE, NOW(), NOW()),
('Lidocaine (as hydrochloride) ', TRUE, NOW(), NOW()),
('Linezolid', TRUE, NOW(), NOW()),
('Lipids', TRUE, NOW(), NOW()),
('Lithium Carbonate ', TRUE, NOW(), NOW()),
('Live Attenuated Bivalent Oral Polio Vaccine (Type 1 and 3)', TRUE, NOW(), NOW()),
('Live Attenuated Measles and Rubella (MR) Vaccine', TRUE, NOW(), NOW()),
('Live Attenuated Measles Vaccine', TRUE, NOW(), NOW()),
('Live Attenuated Measles, Mumps and Rubella (MMR) Vaccine', TRUE, NOW(), NOW()),
('Live Attenuated Mumps Vaccine', TRUE, NOW(), NOW()),
('Live Attenuated Rubella Vaccine', TRUE, NOW(), NOW()),
('Live Attenuated Varicella Vaccine', TRUE, NOW(), NOW()),
('Loperamide (as hydrochloride)', TRUE, NOW(), NOW()),
('Lopinavir + Ritonavir', TRUE, NOW(), NOW()),
('Loratadine', TRUE, NOW(), NOW()),
('Losartan (as potassium salt)', TRUE, NOW(), NOW()),
('Losartan + Hydrochlorothiazide', TRUE, NOW(), NOW()),
('Lynestrenol', TRUE, NOW(), NOW()),
('Magnesium Sulfate (as heptahydrate) ', TRUE, NOW(), NOW()),
('Mannitol', TRUE, NOW(), NOW()),
('Mebendazole', TRUE, NOW(), NOW()),
('Mebeverine (as hydrochloride)', TRUE, NOW(), NOW()),
('Mecobalamin', TRUE, NOW(), NOW()),
('Medroxyprogesterone ', TRUE, NOW(), NOW()),
('Mefenamic Acid', TRUE, NOW(), NOW()),
('Mefloquine (as hydrochloride) ', TRUE, NOW(), NOW()),
('Megestrol (as acetate) ', TRUE, NOW(), NOW()),
('Melphalan ', TRUE, NOW(), NOW()),
('Memantine', TRUE, NOW(), NOW()),
('Meningococcal polysaccharide (Neisseria meningitidis) vaccine', TRUE, NOW(), NOW()),
('Mercaptopurine ', TRUE, NOW(), NOW()),
('Meropenem', TRUE, NOW(), NOW()),
('Mesalazine ', TRUE, NOW(), NOW()),
('Mesna (sodium-2- mercaptoethanesulphonate) (1, 2)', TRUE, NOW(), NOW()),
('Metformin (as hydrochloride)', TRUE, NOW(), NOW()),
('Methimazole (thiamazole)', TRUE, NOW(), NOW()),
('Methotrexate ', TRUE, NOW(), NOW()),
('Methyldopa', TRUE, NOW(), NOW()),
('Methylene Blue ', TRUE, NOW(), NOW()),
('Methylergometrine (methylergonovine) (as hydrogen maleate or maleate) (A2)', TRUE, NOW(), NOW()),
('Methylergonovine (see Methylergometrine)', TRUE, NOW(), NOW()),
('Methylphenidate ', TRUE, NOW(), NOW()),
('Methylprednisolone', TRUE, NOW(), NOW()),
('Metoclopramide', TRUE, NOW(), NOW()),
('Metoprolol (as tartrate)', TRUE, NOW(), NOW()),
('Metronidazole', TRUE, NOW(), NOW()),
('Micafungin', TRUE, NOW(), NOW()),
('Miconazole', TRUE, NOW(), NOW()),
('Micronutrient Powder', TRUE, NOW(), NOW()),
('Midazolam ', TRUE, NOW(), NOW()),
('Mitoxantrone ', TRUE, NOW(), NOW()),
('Modified Fluid Gelatin (polymerisate of degraded succinylated gelatin', TRUE, NOW(), NOW()),
('Monobasic/Dibasic Sodium Phosphate', TRUE, NOW(), NOW()),
('Montelukast (as sodium salt) ', TRUE, NOW(), NOW()),
('Morphine (as sulfate) ', TRUE, NOW(), NOW()),
('Moxifloxacin', TRUE, NOW(), NOW()),
('Multivitamins', TRUE, NOW(), NOW()),
('Mupirocin', TRUE, NOW(), NOW()),
('Mycophenolate Mofetil ', TRUE, NOW(), NOW()),
('Mycophenolic Acid (as Mycophenolate Sodium) ', TRUE, NOW(), NOW()),
('N-acetyl Penicillamine ', TRUE, NOW(), NOW()),
('Nalbuphine (as hydrochloride) ', TRUE, NOW(), NOW()),
('Nalidixic Acid', TRUE, NOW(), NOW()),
('Naloxone (as hydrochloride) ', TRUE, NOW(), NOW()),
('Naltrexone (as hydrochloride)', TRUE, NOW(), NOW()),
('Naproxen (as sodium salt)', TRUE, NOW(), NOW()),
('Neomycin (as sulfate) + Polymixin B (as sulfate) + Fluocinolone Acetonide', TRUE, NOW(), NOW()),
('Neostigmine', TRUE, NOW(), NOW()),
('Nepafenac', TRUE, NOW(), NOW()),
('Nevirapine', TRUE, NOW(), NOW()),
('Nicardipine (as hydrochloride) ', TRUE, NOW(), NOW()),
('Nicotine polacrilex', TRUE, NOW(), NOW()),
('Nicotine transdermal therapeutic system', TRUE, NOW(), NOW()),
('Nifedipine', TRUE, NOW(), NOW()),
('Nimodipine', TRUE, NOW(), NOW()),
('Nitrofurantoin ', TRUE, NOW(), NOW()),
('Nitroglycerin (see Glyceryl Trinitrate)', TRUE, NOW(), NOW()),
('Nitrous Oxide ', TRUE, NOW(), NOW()),
('Norepinephrine (as bitartrate) ', TRUE, NOW(), NOW()),
('Norethisterone (as acetate and as base) ', TRUE, NOW(), NOW()),
('Nystatin', TRUE, NOW(), NOW()),
('Octreotide (as acetate) ', TRUE, NOW(), NOW()),
('Ofloxacin', TRUE, NOW(), NOW()),
('Olanzapine ', TRUE, NOW(), NOW()),
('Olodaterol (as hydrochloride)', TRUE, NOW(), NOW()),
('Omeprazole', TRUE, NOW(), NOW()),
('Ondansetron ', TRUE, NOW(), NOW()),
('Oral Rehydration Salts (ORS 75- replacement)', TRUE, NOW(), NOW()),
('Oseltamivir (as phosphate)', TRUE, NOW(), NOW()),
('Oxacillin (as sodium salt)', TRUE, NOW(), NOW()),
('Oxaliplatin ', TRUE, NOW(), NOW()),
('Oxcarbazepine', TRUE, NOW(), NOW()),
('Oxycodone (as hydrochloride) + Naloxone (as hydrochloride)', TRUE, NOW(), NOW()),
('Oxycodone (as hydrochloride) ', TRUE, NOW(), NOW()),
('Oxygen', TRUE, NOW(), NOW()),
('Oxymetazoline (as hydrochloride)', TRUE, NOW(), NOW()),
('Oxytocin (synthetic) ', TRUE, NOW(), NOW()),
('Paclitaxel ', TRUE, NOW(), NOW()),
('Paliperidone', TRUE, NOW(), NOW()),
('Pancuronium (as bromide) ', TRUE, NOW(), NOW()),
('Pantoprazole', TRUE, NOW(), NOW()),
('Para-amino salicylic acid', TRUE, NOW(), NOW()),
('Paracetamol', TRUE, NOW(), NOW()),
('Peginterferon Alfa 2A ', TRUE, NOW(), NOW()),
('Penicillin G Benzathine (benzathine benzylpenicillin)', TRUE, NOW(), NOW()),
('Penicillin G Crystalline (benyzylpenicillin) (as sodium salt) ', TRUE, NOW(), NOW()),
('Peritoneal Dialysis Solution', TRUE, NOW(), NOW()),
('Permethrin', TRUE, NOW(), NOW()),
('Pethidine (meperidine) (as hydrochloride) ', TRUE, NOW(), NOW()),
('Petrolatum/ petroleum', TRUE, NOW(), NOW()),
('Phenobarbital ', TRUE, NOW(), NOW()),
('Phenoxymethyl Penicillin (penicillin V) (as potassium salt)', TRUE, NOW(), NOW()),
('Phenylephrine (as hydrochloride)', TRUE, NOW(), NOW()),
('Phenytoin (as sodium salt)', TRUE, NOW(), NOW()),
('Phospholipid fraction from bovine lung', TRUE, NOW(), NOW()),
('Physostigmine (as salicylate) ', TRUE, NOW(), NOW()),
('Phytomenadione (phytonadione, vitamin K1)', TRUE, NOW(), NOW()),
('Pilocarpine (as hydrochloride)', TRUE, NOW(), NOW()),
('Piperacillin + Tazobactam (as sodium salt)', TRUE, NOW(), NOW()),
('Pneumococcal Conjugate Vaccine', TRUE, NOW(), NOW()),
('Pneumococcal Polyvalent Vaccine', TRUE, NOW(), NOW()),
('Polymyxin B', TRUE, NOW(), NOW()),
('Poractant alfa', TRUE, NOW(), NOW()),
('Potassium (as citrate)', TRUE, NOW(), NOW()),
('Potassium Chloride', TRUE, NOW(), NOW()),
('Potassium Phosphate', TRUE, NOW(), NOW()),
('Povidone Iodine', TRUE, NOW(), NOW()),
('Pralidoxime Chloride ', TRUE, NOW(), NOW()),
('Praziquantel ', TRUE, NOW(), NOW()),
('Prednisolone', TRUE, NOW(), NOW()),
('Prednisone', TRUE, NOW(), NOW()),
('Primaquine (as diphosphate)', TRUE, NOW(), NOW()),
('Propofol ', TRUE, NOW(), NOW()),
('Propranolol (as hydrochloride)', TRUE, NOW(), NOW()),
('Propylthiouracil', TRUE, NOW(), NOW()),
('Protamine Sulfate ', TRUE, NOW(), NOW()),
('Prothionamide', TRUE, NOW(), NOW()),
('Proxymetacaine (proparacaine) (as hydrochloride)', TRUE, NOW(), NOW()),
('Pyrazinamide', TRUE, NOW(), NOW()),
('Pyridostigmine (as bromide) ', TRUE, NOW(), NOW()),
('Pyridoxine (vitamin B6) (as hydrochloride) ', TRUE, NOW(), NOW()),
('Pyrimethamine ', TRUE, NOW(), NOW()),
('Quetiapine (as fumarate)', TRUE, NOW(), NOW()),
('Quinine', TRUE, NOW(), NOW()),
('Rabeprazole sodium', TRUE, NOW(), NOW()),
('Rabies Immunoglobulin (human)', TRUE, NOW(), NOW()),
('Rabies vaccine, Chick Embryo Cell (purified, inactivated)', TRUE, NOW(), NOW()),
('Rabies vaccine, Vero Cell (purified)', TRUE, NOW(), NOW()),
('Ranitidine (as hydrochloride)', TRUE, NOW(), NOW()),
('Regular, Insulin (recombinant DNA human)', TRUE, NOW(), NOW()),
('Remifentanil', TRUE, NOW(), NOW()),
('Retinol (vitamin A) (as palmitate)', TRUE, NOW(), NOW()),
('Ribavirin', TRUE, NOW(), NOW()),
('Rifabutin', TRUE, NOW(), NOW()),
('Rifampicin', TRUE, NOW(), NOW()),
('Rifapentine', TRUE, NOW(), NOW()),
('Rifaximin', TRUE, NOW(), NOW()),
('Rilpivirine (as hydrochloride)', TRUE, NOW(), NOW()),
('Risperidone', TRUE, NOW(), NOW()),
('Rituximab ', TRUE, NOW(), NOW()),
('Rivastigmine (as hydrogen tartrate)', TRUE, NOW(), NOW()),
('Rocuronium (as bromide) ', TRUE, NOW(), NOW()),
('Ropivacaine (as hydrochloride)', TRUE, NOW(), NOW()),
('Rosuvastatin (as calcium salt)', TRUE, NOW(), NOW()),
('Sacubitril/Valsartan', TRUE, NOW(), NOW()),
('Salbutamol (as sulfate)', TRUE, NOW(), NOW()),
('Salicylic Acid', TRUE, NOW(), NOW()),
('Sambong [Blumea balsamifera (L) DC (Fam. Compositae)] ●', TRUE, NOW(), NOW()),
('Selegiline (as hydrochloride)', TRUE, NOW(), NOW()),
('Selenium Sulfide', TRUE, NOW(), NOW()),
('Sertraline (as hydrochloride)', TRUE, NOW(), NOW()),
('Sevelamer carbonate', TRUE, NOW(), NOW()),
('Sevoflurane ', TRUE, NOW(), NOW()),
('Silver Sulfadiazine', TRUE, NOW(), NOW()),
('Simvastatin ', TRUE, NOW(), NOW()),
('Sirolimus ', TRUE, NOW(), NOW()),
('Sodium Bicarbonate', TRUE, NOW(), NOW()),
('Sodium Calcium Edetate ', TRUE, NOW(), NOW()),
('Sodium Chloride', TRUE, NOW(), NOW()),
('Sodium Dichloroisocyanurate (to be used for water purification)', TRUE, NOW(), NOW()),
('Sodium Hyaluronate', TRUE, NOW(), NOW()),
('Sodium Hypochlorite', TRUE, NOW(), NOW()),
('Sodium Iodide 1311 ', TRUE, NOW(), NOW()),
('Sodium Nitrite ', TRUE, NOW(), NOW()),
('Sodium Nitroprusside ', TRUE, NOW(), NOW()),
('Sodium Sulfate', TRUE, NOW(), NOW()),
('Sodium Thiosulfate ', TRUE, NOW(), NOW()),
('Sodium Valproate', TRUE, NOW(), NOW()),
('Sodium Valproate + Valproic Acid', TRUE, NOW(), NOW()),
('Sofosbuvir', TRUE, NOW(), NOW()),
('Sofosbuvir + ledipasvir', TRUE, NOW(), NOW()),
('Sofosbuvir + velpatasvir', TRUE, NOW(), NOW()),
('Somatostatin ', TRUE, NOW(), NOW()),
('Soya bean oil + Medium chain triglycerides + Olive oil + Purified fish oil', TRUE, NOW(), NOW()),
('Spectinomycin ', TRUE, NOW(), NOW()),
('Spironolactone (K-sparer) (2, B)', TRUE, NOW(), NOW()),
('Standard Senna Concentrate', TRUE, NOW(), NOW()),
('Sterile Water for Injection', TRUE, NOW(), NOW()),
('Streptokinase ', TRUE, NOW(), NOW()),
('Streptomycin (as sulfate)', TRUE, NOW(), NOW()),
('Succimer (dimercapto succinic acid, DMSA)', TRUE, NOW(), NOW()),
('Sucralfate', TRUE, NOW(), NOW()),
('Sugammadex', TRUE, NOW(), NOW()),
('Sulfacetamide + Prednisolone', TRUE, NOW(), NOW()),
('Sulfamethoxazole + Trimethoprim (see Cotrimoxazole)', TRUE, NOW(), NOW()),
('Sulfur', TRUE, NOW(), NOW()),
('Sumatriptan', TRUE, NOW(), NOW()),
('Suxamethonium (succinylcholine) (as chloride)', TRUE, NOW(), NOW()),
('Tacrolimus ', TRUE, NOW(), NOW()),
('Tafluprost', TRUE, NOW(), NOW()),
('Tamoxifen (as citrate) ', TRUE, NOW(), NOW()),
('Tamsulosin', TRUE, NOW(), NOW()),
('Tegafur + Uracil ', TRUE, NOW(), NOW()),
('Telmisartan', TRUE, NOW(), NOW()),
('Telmisartan + Hydrochlorothiazide', TRUE, NOW(), NOW()),
('Tenofovir + Lamivudine + Dolutegravir', TRUE, NOW(), NOW()),
('Tenofovir alafenamide fumarate', TRUE, NOW(), NOW()),
('Tenofovir disoproxil fumarate', TRUE, NOW(), NOW()),
('Terazosin (as hydrochloride)', TRUE, NOW(), NOW()),
('Terbinafine', TRUE, NOW(), NOW()),
('Terbutaline (as sulfate)', TRUE, NOW(), NOW()),
('Testosterone (as undecanoate) ', TRUE, NOW(), NOW()),
('Tetanus Immunoglobulin (human)', TRUE, NOW(), NOW()),
('Tetanus Toxoid', TRUE, NOW(), NOW()),
('Tetracaine', TRUE, NOW(), NOW()),
('Tetracycline', TRUE, NOW(), NOW()),
('Theophylline (anhydrous)', TRUE, NOW(), NOW()),
('Thiamine (Vitamin B1)', TRUE, NOW(), NOW()),
('Thiopental Sodium ', TRUE, NOW(), NOW()),
('Timolol (as maleate)', TRUE, NOW(), NOW()),
('Tinzaparin (as sodium) ', TRUE, NOW(), NOW()),
('Tiotropium (as bromide)', TRUE, NOW(), NOW()),
('Tobramycin', TRUE, NOW(), NOW()),
('Tobramycin + Dexamethasone', TRUE, NOW(), NOW()),
('Tolvaptan', TRUE, NOW(), NOW()),
('Topiramate', TRUE, NOW(), NOW()),
('Trace Elements', TRUE, NOW(), NOW()),
('Tramadol (as hydrochloride) ', TRUE, NOW(), NOW()),
('Tranexamic Acid', TRUE, NOW(), NOW()),
('Trastuzumab ', TRUE, NOW(), NOW()),
('Travoprost', TRUE, NOW(), NOW()),
('Triclabendazole', TRUE, NOW(), NOW()),
('Trimetazidine (as hydrochloride)', TRUE, NOW(), NOW()),
('Tropicamide', TRUE, NOW(), NOW()),
('Tropicamide + phenylephrine hydrochloride', TRUE, NOW(), NOW()),
('Tsaang Gubat ● [Carmona retusa (Vahl) Masam (Fam. Boraginaceae)]', TRUE, NOW(), NOW()),
('Tuberculin, Purified Protein Derivative (PPD)', TRUE, NOW(), NOW()),
('Typhoid Vaccine', TRUE, NOW(), NOW()),
('Ursodeoxycholic Acid', TRUE, NOW(), NOW()),
('Valaciclovir (as hydrochloride)', TRUE, NOW(), NOW()),
('Valganciclovir', TRUE, NOW(), NOW()),
('Valproic Acid', TRUE, NOW(), NOW()),
('Valsartan', TRUE, NOW(), NOW()),
('Valsartan + Hydrochlorothiazide', TRUE, NOW(), NOW()),
('Vancomycin', TRUE, NOW(), NOW()),
('Varenicline', TRUE, NOW(), NOW()),
('Varicella Zoster Immunoglobulin (VZIG)', TRUE, NOW(), NOW()),
('Vecuronium (as bromide)', TRUE, NOW(), NOW()),
('Verapamil (as hydrochloride)', TRUE, NOW(), NOW()),
('Vinblastine (as sulfate) ', TRUE, NOW(), NOW()),
('Vincristine (as sulfate) ', TRUE, NOW(), NOW()),
('Vitamin A (see Retinol)', TRUE, NOW(), NOW()),
('Vitamin B1 B6 B12', TRUE, NOW(), NOW()),
('Vitamin B6 (see Pyridoxine)', TRUE, NOW(), NOW()),
('Vitamin C (see Ascorbic Acid)', TRUE, NOW(), NOW()),
('Vitamin Intravenous, Fat-Soluble', TRUE, NOW(), NOW()),
('Vitamin Intravenous, Water- Soluble', TRUE, NOW(), NOW()),
('Vitamin K1 (see Phytomenadione)', TRUE, NOW(), NOW()),
('Voriconazole', TRUE, NOW(), NOW()),
('Warfarin (as sodium salt) ', TRUE, NOW(), NOW()),
('Yellow Fever Vaccine', TRUE, NOW(), NOW()),
('Zidovudine', TRUE, NOW(), NOW()),
('Zidovudine + Lamivudine', TRUE, NOW(), NOW()),
('Zinc', TRUE, NOW(), NOW()),
('Zolmitriptan', TRUE, NOW(), NOW()),
('Zolpidem', TRUE, NOW(), NOW())